apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorizer-secret-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Mafzaidi/kubernetes-secrets.git
    targetRevision: production
    path: apps/authorizer/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: authorizer-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
