apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorizer-secret-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Mafzaidi/kubernetes-secrets.git
    targetRevision: dev
    path: apps/authorizer-service/overlays/dev
    plugin:
      name: ksops
  destination:
    server: https://kubernetes.default.svc
    namespace: authorizer-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
