apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authorizer-service-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: authorizer=docker.io/mafzaidi93/authorizer-service
    argocd-image-updater.argoproj.io/authorizer.update-strategy: latest
    argocd-image-updater.argoproj.io/authorizer.allow-tags: regexp:^dev$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: dev
spec:
  project: default
  source:
    repoURL: https://github.com/Mafzaidi/kubernetes-manifest.git
    targetRevision: dev
    path: apps/authorizer-service
    helm:
      valueFiles:
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: authorizer-service-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true